"""
Terms of Use page — a standalone module (not part of app.py's main
property/report flow) so branding.py's footer can link to it without a
circular import: branding.py only needs to flip st.session_state["view"] to
"terms" (see render_footer()), while this module owns the actual page
content and can freely import render_header/render_footer itself.
"""
import streamlit as st

from branding import BRAND, render_footer, render_header

TERMS_TEXT = f"""
*Last updated: 2026-07-17*

These Terms of Use ("Terms") govern access to and use of RootedReports (the
"Software"), a listing-activity-report generation tool made available by
{BRAND['agent_name']} ("Licensor"). By accessing or using the Software, the
individual or entity doing so ("Licensee," "you") agrees to be bound by
these Terms. If you do not agree, do not use the Software.

#### 1. Ownership

The Software — including its source code, design, underlying data models,
report templates, and calculation methodology — is the sole property of
{BRAND['agent_name']}. All rights not expressly granted to Licensee under
these Terms are reserved by Licensor.

#### 2. Grant of License

Licensor grants Licensee a limited, non-exclusive, non-transferable,
revocable license to access and use the Software solely to generate listing
activity reports for real estate listings Licensee is actively representing.
This license does not convey any ownership interest in the Software.

#### 3. Restrictions

Licensee may not, and may not permit any third party to:

- copy, modify, or create derivative works of the Software;
- reverse-engineer, decompile, or attempt to derive the Software's source
  code or underlying methodology;
- resell, sublicense, rent, lease, or otherwise redistribute the Software or
  access to it, in whole or in part, without Licensor's prior written
  consent;
- remove or obscure any proprietary notices; or
- use the Software to build or support a product or service that competes
  with it.

#### 4. Licensor's Right to License or Sell

Licensor retains the sole and exclusive right to license, sell, or grant
access to the Software — in whole or in part — to any other real estate
agent, team, or brokerage, on whatever terms and at whatever price Licensor
chooses, without any obligation or accounting to Licensee.

#### 5. Licensee Data and MLS Compliance

Licensee is solely responsible for ensuring that any MLS-sourced data
uploaded to the Software is used in compliance with the rules and usage
restrictions of Licensee's own MLS. Licensor is not responsible for
Licensee's compliance with any third-party data license, including MLS
rules of use.

#### 6. Third-Party Processing

Reports and files uploaded to the Software are processed using Google's
Gemini API to extract listing data, and resulting data is stored using
Google Cloud/Supabase infrastructure to build a history of reports for each
property. By using the Software, Licensee consents to this processing.
Licensor does not sell Licensee data or client data to third parties.

#### 7. Disclaimer of Warranties

THE SOFTWARE IS PROVIDED "AS IS," WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED. Licensor does not warrant that data extraction, calculated
statistics (including but not limited to absorption rates, days-on-market
benchmarks, or price trend figures), or generated commentary are accurate,
complete, or free of error. Licensee is solely responsible for reviewing and
verifying all report contents before relying on them or sharing them with a
client.

#### 8. Limitation of Liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, LICENSOR SHALL NOT BE LIABLE FOR ANY
INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY
LOSS OF PROFITS OR REVENUE, ARISING FROM LICENSEE'S USE OF THE SOFTWARE OR
ANY REPORT GENERATED BY IT, INCLUDING ANY BUSINESS OR CLIENT DECISION MADE IN
RELIANCE ON A REPORT.

#### 9. Term and Termination

This license is effective until terminated. Licensor may suspend or
terminate Licensee's access at any time, with or without cause, including
for any actual or suspected violation of these Terms. Sections 1, 3, 4, 7,
8, and 10 survive termination.

#### 10. Governing Law

These Terms are governed by the laws of the State of North Carolina,
without regard to its conflict-of-laws principles.

#### 11. Changes to These Terms

Licensor may modify these Terms at any time. Continued use of the Software
after a change is posted constitutes acceptance of the revised Terms.

#### 12. Contact

Questions about these Terms may be directed to {BRAND['agent_name']}.

---

*This document was prepared with AI assistance as a starting template and
has not been reviewed by a licensed attorney. It is not a substitute for
independent legal advice, particularly once the Software is being licensed
to other agents or brokerages for a fee.*
"""


def render_terms():
    render_header("Terms of Use", prepared_by=BRAND["agent_name"])
    if st.button("← Back"):
        ret = st.session_state.get("terms_return") or {"view": "menu", "slug": None, "stage": "csv"}
        st.session_state["view"] = ret["view"]
        st.session_state["slug"] = ret["slug"]
        st.session_state["stage"] = ret["stage"]
        st.rerun()
    st.markdown(TERMS_TEXT)
    render_footer()
